apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
spec:
  rules:
  - host: home.ugard.win
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: homepage
              port:
                number: 3000
  tls:
  - hosts:
    - home.ugard.win
    secretName: tls-home-ingress-http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: gethomepage
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: gethomepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: gethomepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Development:
        - ArgoCD:
            href: http://192.168.10.1
            description: GitOps continuous delivery
            icon: argocd
        - Gitea:
            href: https://gitea.ugard.win
            description: Git repository manager
            icon: gitea
        - Drone CI:
            href: https://drone.ugard.win
            description: Continuous integration
            icon: drone

    - Media & Content:
        - Immich:
            href: https://immich.ugard.win
            description: Photo management
            icon: immich
        - Photo Memories:
            href: https://kiosk.ugard.win
            description: Historical photo frame
            icon: photos
        - Jellyfin:
            href: https://jellyfin.ugard.win
            description: Media server
            icon: jellyfin
        - Obsidian:
            href: https://notes.ugard.win
            description: Note taking
            icon: obsidian
        - Paperless:
            href: https://paperless.ugard.win
            description: Document management
            icon: paperless
        - Manyfold:
            href: https://manyfold.ugard.win
            description: 3D model library
            icon: manyfold

    - Productivity:
        - Vikunja:
            href: https://vikunja.ugard.win
            description: Task management
            icon: vikunja
        - Vaultwarden:
            href: https://vault.ugard.win
            description: Password manager
            icon: vaultwarden
        - PicoShare:
            href: https://pico.ugard.win
            description: File sharing
            icon: picoshare

    - Home Automation:
        - Home Assistant:
            href: https://hass.ugard.win
            description: Smart home controller
            icon: homeassistant
        - AdGuard:
            href: http://192.168.10.254
            description: DNS ad blocker
            icon: adguard

    - Monitoring:
        - Healthchecks:
            href: https://hc.ugard.win
            description: Cron job monitoring
            icon: healthchecks
        - Prometheus:
            href: https://monitoring.ugard.win
            description: Metrics monitoring
            icon: prometheus
        - Grafana:
            href: https://grafana.ugard.win
            description: Metrics dashboard
            icon: grafana
  widgets.yaml: |
    - type: healthchecks
      url: https://hc.ugard.win
    - type: prometheus
      url: https://monitoring.ugard.win
    - type: prometheusmetric
      url: https://monitoring.ugard.win
      metrics:
        - label: "Garage Free Space"
          query: 'kubelet_volume_stats_available_bytes{persistentvolumeclaim="garage-data"}'
          format:
            type: bytes
        - label: "Jellyfin Free Space"
          query: 'kubelet_volume_stats_available_bytes{persistentvolumeclaim="media"}'
          format:
            type: bytes
        - label: "rTorrent Free Space"
          query: 'kubelet_volume_stats_available_bytes{persistentvolumeclaim="media-zfs"}'
          format:
            type: bytes
    - type: iframe
      name: "Photo Memories"
      src: "https://kiosk.ugard.win?memories=true&past_memory_days=7&show_time=false&show_date=false&disable_ui=true"
      classes: h-96 w-full
      allowFullscreen: false
      allowScrolling: no
  docker.yaml: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
      - gateways
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: gethomepage
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: gethomepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: gethomepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:v1.9.0"
          imagePullPolicy: Always
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: home.ugard.win # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config/custom.js
              name: homepage-config
              subPath: custom.js
            - mountPath: /app/config/custom.css
              name: homepage-config
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir: {}