image:
  tag: latest
env:
  DRONE_RPC_HOST: "drone"
  DRONE_RPC_PROTO: "http"
  DRONE_LOG_LEVEL: "info"
  DRONE_KUBERNETES_ENABLED: "true"
  DRONE_KUBERNETES_NAMESPACE: "drone"
  DRONE_KUBERNETES_PRIVILEGED: "false"
  DRONE_KUBERNETES_VOLUME_SIZE_LIMIT: "1Gi"
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
replicaCount: 1
