env:
  DRONE_RPC_HOST: "drone"
  DRONE_RPC_PROTO: "http"
  DRONE_NAMESPACE_DEFAULT: "drone"
extraSecretNamesForEnvFrom:
  - drone-runner
rbac:
  buildNamespaces:
    - drone
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
replicaCount: 1
