apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - namespace.yaml
  # - immich.pvc.yaml
  # - migrate.yaml
  # - ftp-service.yaml
  - rclone_secret.yaml
  - bridge-service.yaml
