apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drone
resources:
  - secret.yaml
patches:
- patch: |
    - op: add
      path: /rules/-
      value:
        apiGroups: [""]
        resources: ["pods", "pods/log", "configmaps"]
        verbs: ["get", "list", "watch", "create", "patch", "delete"]
    - op: add
      path: /rules/-
      value:
        apiGroups: [""]
        resources: ["pods/exec"]
        verbs: ["create"]
  target:
    kind: Role
    name: drone-runner-kube
- patch: |
    - op: replace
      path: /subjects/0/namespace
      value: drone
  target:
    kind: RoleBinding
    name: drone-runner-kube
