apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - openarchiver.pvc.yaml
  - valkey.pvc.yaml
  - meilisearch.pvc.yaml
  - openarchiver.deployment.yaml
  - openarchiver.service.yaml
  - openarchiver.ingress.yaml
  - openarchiver.sealed_secret.yaml
  - valkey.deployment.yaml
  - valkey.service.yaml
  - meilisearch.deployment.yaml
  - meilisearch.service.yaml
  - tika.deployment.yaml
  - tika.service.yaml
  - migrate.yaml
