apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-actions-runner
  namespace: gitea
data:
  config.yaml: |
    log.level: info
    runner:
      capacity: 1
      labels:
        - ubuntu-latest
        - self-hosted
        - linux
        - global
      executor: shell


