apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-actions-runner
  namespace: gitea
  labels:
    app: gitea-actions-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-actions-runner
  template:
    metadata:
      labels:
        app: gitea-actions-runner
    spec:
      serviceAccountName: gitea-actions-runner
      containers:
      - name: dind
        image: docker:latest
        command:
          - dockerd
          - --host=unix:///var/run/docker.sock
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-state
          mountPath: /var/run
      - name: runner
        image: gitea/act_runner:latest
        args:
          - daemon
          - --config
          - /config.yaml
        env:
        - name: GITEA_INSTANCE_URL
          value: "http://gitea-web.gitea:80"
        - name: GITEA_RUNNER_REGISTRATION_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitea-actions-runner
              key: GITEA_RUNNER_REGISTRATION_TOKEN
        volumeMounts:
        - name: config
          mountPath: /config.yaml
          subPath: config.yaml
        - name: docker-state
          mountPath: /var/run
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
      volumes:
      - name: config
        configMap:
          name: gitea-actions-runner
      - name: docker-state
        emptyDir: {}
