apiVersion: v1
kind: Service
metadata:
  name: healthchecks
  namespace: healthchecks
  labels:
    app: healthchecks
spec:
  selector:
    app: healthchecks
  ports:
    - port: 80
      targetPort: 8000
      name: http
  type: ClusterIP
