---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-config-json
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBnWhe8Qi8N3a7P+PNkKXFPqaisae0/Lgu7F2032fDz2uSiwtbqpDZyNLTlbIXM06A1jEEDtYRPcYZ7ApdzLmB3tVWgFn6sCsAnWUHRB9yblUe8WcUp9X5Xii8btjDp9NoHeFceT6pD/3XJgBNfztvs7QrLJtiog1XfMo0FWoKoghcK8ecWBNpLn1+AmuDuchhgN81E2uddiSXEBLqkrREiQ7T36T5DJcCBye9fd0WknvIRmnVFBy89Hi91oEGHLPS2KmmEWW9f5dgXq0icEc4xqbPX1lqVtfo7tUMVVOU+b6ZckzHEwqVrJGaQ7Z2PSwSRScZMYRqFHhLcpXWf8aUPYbEn1L0JdhEBHMCtXobkVZ7Hu53C7pbbQ12cQS2LirEQrQGm19MozvIALsVFuOACouL3xeHuInw0tdZQrX52m8gtzbfbEz/1/zJFLEX1/lPJ6W4Eb6TcyQymhqNgL2WkVy+IaMEU8JgvOmr2qz6XKEuKZeWioYPmHDyQbYdQ0pOHhrKZCItFPSscMKEVEfDIWPDZZfj+fAWte9dAKjvSHcPk0RQZf/P2RRF1S9H/W574M6XvuAO3e3a7t5VOFjkhKTc20fNh+bVRz7WPWSxN5fGx2qAe9z/eJ4+vL+HUIWk0t1EbNvqzpLc+j+nEoFXN/quN3n0o56z2d4JYnXHAold/MONpaHA4FK15h2EKCwyl75p0x82VD26EY8x5JK1W5MWD+ij5FwLeMws18dcgu7UjR2b3A/G8FCmQkaGU5LNByEvJyMrIRsMFSgOrUjCo/mAjH3L6FUn8UhTYLJSXbRg/uFX3OjrC9CBnln2e1vupuec6SJUpeuqpwJXjAubhRpIRUeSP3KR2DbzDZQd0pXR9LyoAwyKU4qvXXt2r6fEXxXcWnEvMtME0yY5H03bXDX6q70d7g+cmjfXH9NqN
  template:
    metadata:
      name: cloudflared-config-json
      namespace: cloudflared
    type: Opaque
